# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DetectObjectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import cv2
import numpy as np

from detectors import sift, orb, surf


class DetectObjectWindow(QtWidgets.QMainWindow):
    def __init__(self, parent, file_name):
        super(DetectObjectWindow, self).__init__(parent)
        self.setObjectName("DetectObjectWindow")
        self.resize(1048, 699)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 40, 421, 431))
        self.label.setPixmap(QtGui.QPixmap(file_name).scaled(421, 431))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QLabel(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(590, 50, 421, 431))
        self.frame.setObjectName("frame")
        self.siftButton = QtWidgets.QPushButton(self.centralwidget)
        self.siftButton.setGeometry(QtCore.QRect(130, 540, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.siftButton.setFont(font)
        self.siftButton.setObjectName("siftButton")
        self.surfButton = QtWidgets.QPushButton(self.centralwidget)
        self.surfButton.setGeometry(QtCore.QRect(440, 540, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.surfButton.setFont(font)
        self.surfButton.setObjectName("surfButton")
        self.orbButton = QtWidgets.QPushButton(self.centralwidget)
        self.orbButton.setGeometry(QtCore.QRect(740, 540, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.orbButton.setFont(font)
        self.orbButton.setObjectName("orbButton")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        self.siftButton.clicked.connect(lambda: self.sift_detect(file_name))
        self.surfButton.clicked.connect(lambda: self.surf_detect(file_name))
        self.orbButton.clicked.connect(lambda: self.orb_detect(file_name))
        QtCore.QMetaObject.connectSlotsByName(self)

    def sift_detect(self, file_name):
        img = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)
        cap = cv2.VideoCapture('IMG_0076.MOV')
        sift(img, cap)

    def orb_detect(self, file_name):
        img = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)
        cap = cv2.VideoCapture('IMG_0076.MOV')
        orb(img, cap)
    def surf_detect(self, file_name):
        img = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)
        cap = cv2.VideoCapture('IMG_0076.MOV')
        surf(img, cap)
    def retranslateUi(self, DetectObjectWindow):
        _translate = QtCore.QCoreApplication.translate
        DetectObjectWindow.setWindowTitle(_translate("DetectObjectWindow", "Окно отслеживания"))
        self.siftButton.setText(_translate("DetectObjectWindow", "SIFT"))
        self.surfButton.setText(_translate("DetectObjectWindow", "SURF"))
        self.orbButton.setText(_translate("DetectObjectWindow", "ORB"))


